GET http://localhost:7000/products

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "simon@simon.com",
  "firstName": "Simon",
  "lastName": "Dwyer",
  "password": "123456"
}
###
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "simon@simon.com",
  "password": "123456"
}