
GET http://localhost:7000/wishlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uQHNpbW9uLmNvbSIsIm5hbWUiOiJTaW1vbiIsImlhdCI6MTUxMjY5NDYwMywiZXhwIjoxNTEzMjk5NDAzLCJzdWIiOiI1YTI3NTBiNGUyNmM5ODFjMjUzNTAyY2EifQ.jzx9kZS1tTbIWMz1ISZSY82Wd-l1AtUJECRrjTpZvjY

### Add not existing product to wishlist
POST http://localhost:7000/wishlist/products/WRONG
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uQHNpbW9uLmNvbSIsIm5hbWUiOiJTaW1vbiIsImlhdCI6MTUxMjY5NDYwMywiZXhwIjoxNTEzMjk5NDAzLCJzdWIiOiI1YTI3NTBiNGUyNmM5ODFjMjUzNTAyY2EifQ.jzx9kZS1tTbIWMz1ISZSY82Wd-l1AtUJECRrjTpZvjY

### Add existing product to wishlist
POST http://localhost:7000/wishlist/products/5a29f2f6d6cf8f1e7e6a68de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uQHNpbW9uLmNvbSIsIm5hbWUiOiJTaW1vbiIsImlhdCI6MTUxMjY5NDYwMywiZXhwIjoxNTEzMjk5NDAzLCJzdWIiOiI1YTI3NTBiNGUyNmM5ODFjMjUzNTAyY2EifQ.jzx9kZS1tTbIWMz1ISZSY82Wd-l1AtUJECRrjTpZvjY

### Remove product from wishlist
DELETE http://localhost:7000/wishlist/products/5a2742b394dc6614a82c219b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbW9uQHNpbW9uLmNvbSIsIm5hbWUiOiJTaW1vbiIsImlhdCI6MTUxMjY5NDYwMywiZXhwIjoxNTEzMjk5NDAzLCJzdWIiOiI1YTI3NTBiNGUyNmM5ODFjMjUzNTAyY2EifQ.jzx9kZS1tTbIWMz1ISZSY82Wd-l1AtUJECRrjTpZvjY
###